### PR TITLE
add Gitter iM badge

### PR DESCRIPTION
**Pull request by cybernet**
i saw that you have a room on gitter and i'm trying to make it active :)

### CODE REVIEW

**Comment by panique** [comment]
:) Very good! Thanks, I'll merge this in a few seconds

**Comment by VoronoZ** [comment]
Fatal error: Call to undefined function password_hash() in D:\OpenServer\OpenServer\domains\test3.ru\application\models\login_model.php on line 464

**Comment by VoronoZ** [comment]
Fatal error: Call to undefined function password_verify() in D:\OpenServer\OpenServer\domains\test3.ru\application\models\login_model.php on line 73
Call Stack

**Comment by panique** [comment]
@VoronoZ Dude, WTF ? Stop posting your stupid error messages here, especially in totally unrelated threads.

Once again and - sorry dude - you'll get a permaban.

**Pull request merged**
